version: "3"

services:
  app:
    build:
      context: .
      network: host
    container_name: "${APP_NAME}"
    restart: "always"
    ports:
      - "${PORT}:5000"
    volumes:
      - ./${APP_NAME}_data:/srv
      - ./${APP_NAME}_data/static:/srv/static
    environment:
      DEBUG: ${DEBUG}
      DATABASE_FILENAME: ${DATABASE_FILENAME}
      PASSWORD_SALT: ${PASSWORD_SALT}
      SECRET: ${SECRET}
